### ISSUE TITLE
FromOwl.generateGraph class cast exception

### ISSUE THREAD

**Issue by beckyjackson** [geneontology/obographs#41]
From @dosumis , migrated from https://github.com/ontodev/robot/issues/260

>I'd like to generate a JSON version of http://purl.obolibrary.org/obo/geno.owl (there doesn't appear to be a release with this conversion). JSON conversion works fine for the various OBO ontologies I've tried but geno.owl =>

```
java.lang.ClassCastException: uk.ac.manchester.cs.owl.owlapi.OWLAnonymousIndividualImpl cannot be cast to org.semanticweb.owlapi.model.OWLLiteral
at org.geneontology.obographs.owlapi.FromOwl.generateGraph(FromOwl.java:477)
at org.geneontology.obographs.owlapi.FromOwl.generateGraphDocument(FromOwl.java:110)
at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:441)
at org.obolibrary.robot.IOHelper.saveOntology(IOHelper.java:414)
at org.obolibrary.robot.ConvertCommand.execute(ConvertCommand.java:130)
at org.obolibrary.robot.CommandManager.executeCommand(CommandManager.java:219)
at org.obolibrary.robot.CommandManager.execute(CommandManager.java:161)
at org.obolibrary.robot.CommandManager.main(CommandManager.java:121)
at org.obolibrary.robot.CommandLineInterface.main(CommandLineInterface.java:53)
```

**Comment by cmungall** [comment]
Can't reproduce, this works for me:

`robot convert -I http://purl.obolibrary.org/obo/geno.owl -o /tmp/geno.owl`
